### ISSUE TITLE
请问有QMIX和LICA样本效率的对比数据吗？

### ISSUE THREAD

**Issue by hijkzzz** [LICA897/LICA#1]
LICA很有意思
但是好像paper中没有提供样本效率的对比
比较的是迭代训练次数？是否有相同step的对比数据？
后面想参考LICA做一些研究 感谢！！

**Comment by mzho7212** [comment]
你好，谢谢你关注这个工作！！由于文章的review process已经结束了，我们将会把LICA official repo迁移到https://github.com/mzho7212/LICA。因为我们将LICA设计成一种on-policy算法，没有一种很好的方式将on-policy算法和off-policy算法通过sample efficiency直接做fair comparison。现在我们正在补充额外的一些value based算法训练的数据（所有算法使用一致的batch size，timestep，number of batch updates）,  而且也会在新paper版本里提供更多training setting细节 (新版本会尽快更新）。 我们也打算中将LICA转化为off-policy in future work。谢谢！
